default: &default
  adapter: postgresql
  encoding: unicode
  username: pedro
  password: toor
  
development:
  <<: *default
  database: onebitflix_development

test:
  <<: *default
  database: onebitflix_test